{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: todo-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: todo-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: todo/app
{{- end }}