apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}