apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: todo-worker:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: todo-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"