name: build-worker

on:
    push:
        branches: [main]
        paths:
            - "worker/**"
            - "Dockerfile.worker"

jobs:
    build:
        uses: ./.github/workflows/docker-build.yaml
        with:
            service: worker
            dockerpath: Dockerfile.worker
        secrets: inherit