name: docker-build

on:
    workflow_call:
        inputs:
            service:
                required: true
                type: string
            dockerpath:
                required: true
                type: string
            push:
                required: false
                type: boolean
                default: true
        secrets:
            DOCKERHUB_USERNAME:
                required: false
            DOCKERHUB_TOKEN:
                required: false

jobs:   
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to DockerHub
              if: ${{ inputs.push }}
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ${{ inputs.dockerpath }}
                push: ${{ inputs.push }}
                tags: |
                    taufik041/todo-${{ inputs.service }}:latest
                    taufik041/todo-${{ inputs.service }}:${{ github.sha }}